@ExpenseTracker.Api_HostAddress = http://localhost:5176   

###Показать все расходы (список)
GET {{ExpenseTracker.Api_HostAddress}}/expenses
Accept: application/json

###Добавить расход
POST {{ExpenseTracker.Api_HostAddress}}/expenses
Content-Type: application/json

{
  "amount": 250,
  "category": "food"
}
