@ExpenseTracker.Api_HostAddress = http://localhost:5176   

###Показать все расходы (список)
GET {{ExpenseTracker.Api_HostAddress}}/expenses
Accept: application/json

###Добавить расход
POST {{ExpenseTracker.Api_HostAddress}}/expenses
Content-Type: application/json

{
  "amount": 20,
  "category": "good"
}

###Удалить расход по индексу
DELETE {{ExpenseTracker.Api_HostAddress}}/expenses/1


###Изменить данные определенного расхода
PUT {{ExpenseTracker.Api_HostAddress}}/expenses/2
Content-Type: application/json

{
  "amount": 10,
  "category": "chips"
}